name: Python Tests

on:
  push:
    branches:
      - develop
    # paths:
    #   - 'beratools/**'  # file changes inside "beratools" will trigger the action 
  pull_request:
    branches:
      - develop
    # paths:
    #   - 'beratools/**'  # file changes inside "beratools" will trigger the action 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.11'
          auto-update-conda: true

      - name: Initialize Conda
        run: |
          conda init bash  # Initialize Conda for the shell environment
          source ~/.bashrc  # Reload the shell configuration

      - name: Create Conda Environment
        run: |
          conda env create -f conda_environment.yml 

      - name: Activate Environment and Run Tests
        run: |
          conda activate bera  # Activate your environment
          pytest --maxfail=1 --disable-warnings -v