name: Python Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.x'
          auto-update-conda: true

      - name: Create Conda Environment
        run: |
          conda env create -f conda_environment.yml 

      - name: Activate Environment and Run Tests
        run: |
          conda activate bera  # Activate your environment
          pytest --maxfail=1 --disable-warnings -v