name: Python Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest  # Use Linux runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.11'
          auto-update-conda: true

      - name: Initialize Conda
        run: |
          conda init bash  # Initialize conda for bash
          source ~/.bashrc  # Reload bash configuration

      - name: Create Conda Environment
        run: |
          conda env create -f conda_environment.yml  # Create environment from environment.yml

      - name: Activate Conda Environment and Run Tests
        run: |
          # Explicitly load Conda to ensure `conda activate` works
          source ~/.bashrc  # Reload the configuration to ensure conda is available
          conda activate bera  # Activate the 'bera' environment
          pytest --maxfail=1 --disable-warnings -v  # Run tests
