name: Python Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.11'
          auto-update-conda: true

      - name: Initialize Conda
        run: |
          conda init bash
          source ~/.bashrc

      - name: Create Conda Environment
        run: |
          conda env create -f conda_environment.yml

      - name: Activate Conda Environment and Run Tests
        run: |
          source ~/.bashrc  
          conda activate bera
          pytest tests/test_workflow.py --maxfail=1 --disable-warnings -s -v 
